### PR TITLE
feat: Catch auth session between requests

### PR DESCRIPTION
**Pull request by Allda**
The auth module is now cached and reused for folloup registry requests.

Previously each request to registry initialized a new session which lead to reset the access token and need of establish secret session all over again. This is now fixed and leads to huge performance improvement when making multiple queries to a registry.

JIRA: ISV-4429

### CODE REVIEW

**Comment by Allda** [comment]
Fixes https://github.com/Allda/coregio/issues/15

**Comment by Allda** [comment]
@staticf0x @mantomas Please review.

Here are some stats for comparison when getting manifest for 400 tags:

```
Before:
Max: 5.92461895942688
Min: 1.3379034996032715
Avg: 1.5465453004837035
Total: 618.6181201934814
Count: 400

Afrer:
Max: 0.952294111251831
Min: 0.4583868980407715
Avg: 0.5130592679977417
Total: 205.22370719909668
Count: 400

```

**Comment by mantomas** [comment]
Makes sense to me, good speed-up 👍🏻

**Comment by staticf0x** [comment]
LGTM, thank you

**Pull request merged**
